//! Main rendering and event processing for the application.

use std::sync::mpsc;
use std::time::{Duration, Instant};

use crate::config::Config;

use anyhow::{anyhow, Result};

use ratatui::{
    prelude::{Buffer, Constraint, Direction, Layout, Position, Rect},
    text::{Line, Span},
    widgets::{StatefulWidget, Widget},
    DefaultTerminal, Frame,
};

use crossterm::event::{
    Event as CrosstermEvent, KeyEvent, KeyEventKind, MouseButton, MouseEvent,
    MouseEventKind,
};

use serde::Deserialize;

use crate::command::Command;
use crate::device_type::DeviceType;
use crate::event::Event;
use crate::object::ObjectId;
use crate::object_list::{ObjectList, ObjectListWidget};
use crate::state::{State, StateDirty};
use crate::view::{self, ListType, View};

#[cfg(feature = "trace")]
use crate::{trace, trace_dbg};

/// A UI action.
///
/// Used internally as the result of input events.
///
/// Also generated by interaction with [`MouseArea`]s.
#[derive(Debug, Clone, Copy, Deserialize)]
pub enum Action {
    SelectTab(usize),
    MoveUp,
    MoveDown,
    TabLeft,
    TabRight,
    OpenDropdown,
    CloseDropdown,
    SelectDropdown,
    #[serde(skip_deserializing)]
    SelectObject(ObjectId),
    #[serde(skip_deserializing)]
    SetTarget(view::Target),
    ToggleMute,
    SetAbsoluteVolume(f32),
    SetRelativeVolume(f32),
    SetDefault,
    Exit,
    // This can be used to delete a default keybinding - make it do nothing.
    Nothing,
}

struct Tab {
    title: String,
    list: ObjectList,
}

impl Tab {
    fn new(title: String, list: ObjectList) -> Self {
        Self { title, list }
    }
}

// Mouse events matching one of the MouseEventKinds within the Rect will
// perform the Actions.
pub type MouseArea = (Rect, Vec<MouseEventKind>, Vec<Action>);

/// Handles the main UI for the application.
///
/// This runs the main loop to process PipeWire events and terminal input and
/// to render the main tabs of the application.
pub struct App {
    /// If set, tells the main loop it's time to exit
    exit: bool,
    /// [`Command`](`crate::command::Command`) channel
    tx: pipewire::channel::Sender<Command>,
    /// [`Event`](`crate::event::Event`) channel
    rx: mpsc::Receiver<Event>,
    /// An error message to return to [`main`](`crate::main`) on exit
    error_message: Option<String>,
    /// The main tabs
    tabs: Vec<Tab>,
    /// The index of the currently-visible tab
    selected_tab_index: usize,
    /// Areas populated during rendering which define actions corresponding to
    /// mouse activity
    mouse_areas: Vec<MouseArea>,
    /// The monitor has received all initial information
    is_ready: bool,
    /// The current PipeWire state
    state: State,
    /// A rendering view based on the current PipeWire state
    view: View,
    /// The application configuration
    config: Config,
}

impl App {
    pub fn new(
        tx: pipewire::channel::Sender<Command>,
        rx: mpsc::Receiver<Event>,
        config: Config,
    ) -> Self {
        let tabs = vec![
            Tab::new(
                String::from("Playback"),
                ObjectList::new(ListType::Node(view::NodeType::Playback), None),
            ),
            Tab::new(
                String::from("Recording"),
                ObjectList::new(
                    ListType::Node(view::NodeType::Recording),
                    None,
                ),
            ),
            Tab::new(
                String::from("Output Devices"),
                ObjectList::new(
                    ListType::Node(view::NodeType::Output),
                    Some(DeviceType::Sink),
                ),
            ),
            Tab::new(
                String::from("Input Devices"),
                ObjectList::new(
                    ListType::Node(view::NodeType::Input),
                    Some(DeviceType::Source),
                ),
            ),
            Tab::new(
                String::from("Configuration"),
                ObjectList::new(ListType::Device, None),
            ),
        ];
        App {
            exit: Default::default(),
            tx,
            rx,
            error_message: Default::default(),
            tabs,
            selected_tab_index: Default::default(),
            mouse_areas: Default::default(),
            is_ready: Default::default(),
            state: Default::default(),
            view: Default::default(),
            config,
        }
    }

    pub fn run(mut self, terminal: &mut DefaultTerminal) -> Result<()> {
        #[cfg(feature = "trace")]
        trace::initialize_logging()?;

        let frame_duration =
            self.config.fps.map_or(Default::default(), |fps| {
                Duration::from_secs_f32(1.0 / fps)
            });
        let mut next_frame_time = Instant::now();

        // Did we handle any events and thus need to re-render?
        let mut needs_render = true;

        while !self.exit {
            // Update view if needed
            match self.state.dirty {
                StateDirty::Everything => {
                    self.view = View::from(&self.state, &self.config.names);
                }
                StateDirty::PeaksOnly => {
                    self.view.update_peaks(&self.state);
                }
                _ => {}
            }
            self.state.dirty = StateDirty::Clean;

            #[cfg(feature = "trace")]
            trace_dbg!(&self.view);

            if self.is_ready
                && self.tabs[self.selected_tab_index].list.selected.is_none()
            {
                self.handle_action(Action::MoveDown);
            }

            let now = Instant::now();
            if needs_render && now >= next_frame_time {
                needs_render = false;
                next_frame_time = now + frame_duration;

                self.mouse_areas.clear();

                terminal.draw(|frame| {
                    self.tabs[self.selected_tab_index]
                        .list
                        .update(frame.area(), &self.view);

                    self.draw(frame);
                })?;
            }

            needs_render |= self.handle_events(
                // If there's no fps limit, we definitely rendered in this
                // iteration, so needs_render is false, and there is no timeout.
                needs_render.then_some(next_frame_time - Instant::now()),
            )?;
        }

        self.error_message.map_or(Ok(()), |s| Err(anyhow!(s)))
    }

    fn draw(&mut self, frame: &mut Frame) {
        let widget = AppWidget {
            selected_tab_index: self.selected_tab_index,
            view: &self.view,
            config: &self.config,
        };
        let mut widget_state = AppWidgetState {
            mouse_areas: &mut self.mouse_areas,
            tabs: &mut self.tabs,
        };

        frame.render_stateful_widget(widget, frame.area(), &mut widget_state);
    }

    fn exit(&mut self, error_message: Option<String>) {
        self.exit = true;
        self.error_message = error_message;
    }

    /// Handle events with optional timeout.
    /// Returns true if events were handled.
    fn handle_events(&mut self, timeout: Option<Duration>) -> Result<bool> {
        let mut were_events_handled = match timeout {
            Some(timeout) => match self.rx.recv_timeout(timeout) {
                Ok(event) => self.handle_event(event)?,
                Err(mpsc::RecvTimeoutError::Timeout) => return Ok(false),
                Err(e) => return Err(e.into()),
            },
            // Block on the next event.
            None => self.handle_event(self.rx.recv()?)?,
        };
        // Then handle the rest that are available.
        while let Ok(event) = self.rx.try_recv() {
            were_events_handled |= self.handle_event(event)?;
        }

        Ok(were_events_handled)
    }

    fn handle_event(&mut self, event: Event) -> Result<bool> {
        #[cfg(feature = "trace")]
        trace_dbg!(&event);

        match event {
            Event::Input(event) => Ok(self.handle_input_event(event)),
            Event::Error(error) => {
                match error {
                    // These happen when objects are removed while the monitor
                    // is still in the process of setting up listeners.
                    error if error.starts_with("no global ") => {}
                    error if error.starts_with("unknown resource ") => {}
                    // I see this one when disconnecting a Bluetooth sink.
                    error if error == "Received error event" => {}
                    _ => self.exit(Some(error)),
                }
                Ok(false) // This makes sense for now.
            }
            Event::Ready => {
                self.is_ready = true;
                Ok(true)
            }
            Event::Monitor(event) => {
                for command in self.state.update(event) {
                    // Filter out capture commands if capture is disabled
                    match command {
                        Command::NodeCaptureStart(..)
                        | Command::NodeCaptureStop(..)
                            if !self.config.peaks => {}
                        command => {
                            let _ = self.tx.send(command);
                        }
                    }
                }
                Ok(true)
            }
        }
    }

    fn handle_input_event(&mut self, event: CrosstermEvent) -> bool {
        match event {
            CrosstermEvent::Key(key_event)
                if key_event.kind == KeyEventKind::Press =>
            {
                self.handle_key_event(key_event)
            }
            CrosstermEvent::Mouse(mouse_event) => {
                self.handle_mouse_event(mouse_event)
            }
            CrosstermEvent::Resize(..) => true,
            _ => false,
        }
    }

    fn handle_key_event(&mut self, key_event: KeyEvent) -> bool {
        if let Some(&action) = self.config.keybindings.get(&key_event) {
            self.handle_action(action);
            return true;
        }

        false
    }

    fn handle_mouse_event(&mut self, mouse_event: MouseEvent) -> bool {
        let actions = self
            .mouse_areas
            .iter()
            .rev()
            .find(|(rect, kinds, _)| {
                rect.contains(Position {
                    x: mouse_event.column,
                    y: mouse_event.row,
                }) && kinds.contains(&mouse_event.kind)
            })
            .map(|(_, _, action)| action.clone())
            .into_iter()
            .flatten();

        let mut handled_action = false;
        for action in actions {
            handled_action = true;
            self.handle_action(action);
        }

        handled_action
    }

    fn handle_action(&mut self, action: Action) {
        match action {
            Action::SelectTab(index) => self.selected_tab_index = index,
            Action::MoveDown => {
                self.tabs[self.selected_tab_index].list.down(&self.view);
            }
            Action::MoveUp => {
                self.tabs[self.selected_tab_index].list.up(&self.view);
            }
            Action::TabLeft => {
                self.selected_tab_index =
                    self.selected_tab_index.checked_sub(1).unwrap_or(4)
            }
            Action::TabRight => {
                self.selected_tab_index = (self.selected_tab_index + 1) % 5
            }
            Action::OpenDropdown => {
                self.tabs[self.selected_tab_index]
                    .list
                    .dropdown_open(&self.view);
            }
            Action::CloseDropdown => {
                self.tabs[self.selected_tab_index].list.dropdown_close();
            }
            Action::SelectDropdown => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .dropdown_select(&self.view);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::SetTarget(target) => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .set_target(&self.view, target);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::SelectObject(object_id) => {
                self.tabs[self.selected_tab_index].list.selected =
                    Some(object_id)
            }
            Action::ToggleMute => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .toggle_mute(&self.view);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::SetAbsoluteVolume(volume) => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .set_absolute_volume(&self.view, volume);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::SetRelativeVolume(volume) => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .set_relative_volume(&self.view, volume);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::SetDefault => {
                let commands = self.tabs[self.selected_tab_index]
                    .list
                    .set_default(&self.view);
                for command in commands {
                    let _ = self.tx.send(command);
                }
            }
            Action::Exit => {
                self.exit(None);
            }
            Action::Nothing => {} // Do nothing!
        }
    }
}

pub struct AppWidget<'a> {
    selected_tab_index: usize,
    view: &'a View,
    config: &'a Config,
}

pub struct AppWidgetState<'a> {
    mouse_areas: &'a mut Vec<MouseArea>,
    tabs: &'a mut Vec<Tab>,
}

impl<'a> StatefulWidget for AppWidget<'a> {
    type State = AppWidgetState<'a>;

    fn render(self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        let layout = Layout::default()
            .direction(Direction::Vertical)
            .constraints([
                Constraint::Min(0),    // list_area
                Constraint::Length(1), // menu_area
            ])
            .split(area);
        let list_area = layout[0];
        let menu_area = layout[1];

        let constraints: Vec<_> = state
            .tabs
            .iter()
            .map(|tab| Constraint::Length(tab.title.len() as u16 + 2))
            .collect();

        let menu_areas = Layout::default()
            .direction(Direction::Horizontal)
            .constraints(constraints)
            .split(menu_area);

        for (i, tab) in state.tabs.iter().enumerate() {
            let title_line = if i == self.selected_tab_index {
                Line::from(vec![
                    Span::styled(
                        &self.config.char_set.tab_marker_left,
                        self.config.theme.tab_marker,
                    ),
                    Span::styled(&tab.title, self.config.theme.tab_selected),
                    Span::styled(
                        &self.config.char_set.tab_marker_right,
                        self.config.theme.tab_marker,
                    ),
                ])
            } else {
                Line::from(Span::styled(
                    format!(" {} ", tab.title),
                    self.config.theme.tab,
                ))
            };
            title_line.render(menu_areas[i], buf);

            state.mouse_areas.push((
                menu_areas[i],
                vec![MouseEventKind::Down(MouseButton::Left)],
                vec![Action::SelectTab(i)],
            ));
        }

        let mut widget = ObjectListWidget {
            object_list: &mut state.tabs[self.selected_tab_index].list,
            view: self.view,
            config: self.config,
        };
        widget.render(list_area, buf, state.mouse_areas);
    }
}
